### PR TITLE
Windows release artifact

### PR DESCRIPTION
**Pull request by hannesa2**
Now release comes with Windows artifact. 

Thanks to Jens R. !

### CODE REVIEW

**Comment by alexmucde** [comment]
macOS build fails

**Comment by hannesa2** [comment]
It needs #186 too.
I rebased it

**Comment by hannesa2** [comment]
@alexmucde It builds now again

**Comment by hannesa2** [comment]
Yes !
All is green, seems #185 is solved 👍

**Review by alexmucde — APPROVED** [review]

**Pull request merged**
