### PR TITLE
Enable optional append for default filters

### LINKED ISSUE #128: Allow Append from the default filter folder
Appending of a filter from the default filter folder would be useful.

### PR DESCRIPTION
**Pull request by m42e**
If the checkbox is activated and default filter is selected it is
appended rather than replacing the previous filters.

Fixes #128

### CODE REVIEW

**Comment by alexmucde** [comment]
I tried this new feature, but it was hard for me at the beginning to underdstand, where the "Append Filter" checkbox belongs to and what it really does. After some tries i understood that instead of switching the filter you will append the selected filter configuration to the current filter.

The original idea of default filter was that you the filter index are stored in the cache , which are generated in parallel and you can quickly switch between different filter configuration. This  new feature will not be able to switch quickly between filter configurations, when you append the current filter.

Perhaps you can move the checkbox beside or under the Default Filter list, that the user knows that it belongs to this feature.

**Comment by m42e** [comment]
Ok i thought this looks a bit messy, too. Maybe I put it in a line just below the selectbox

**Review by alexmucde — APPROVED** [review]
Looks good now, tested with Qt 5.12.9 and MSVC2015 under Windows.

**Comment by alexmucde** [comment]
Github cannot merge. Please can you manually rebase to master?

**Comment by alexmucde** [comment]
Merge worked, will check if it also compiles.

**Pull request merged**
