### PR TITLE
Fix:Linker error with stdc++ library in linux version

### PR DESCRIPTION
**Pull request by ashrivani**

### CODE REVIEW

**Comment by alexmucde** [comment]
@ashrivani Please add also here the signed off statement

**Comment by ashrivani** [comment]
Signed-off-by: Shrivani
shrivani@kpit.com

**Comment by alexmucde** [comment]
No, you must change the commit and add the signed-off statement to your commit message.
Can you update the pull request?

**Comment by ashrivani** [comment]
Okay

**Comment by alexmucde** [comment]
There is now a conflict because of another pull request i have integrated. Can you also fix this?

**Comment by ashrivani** [comment]
@alexmucde :Kindly close this pull request and consider the pull request 
https://github.com/GENIVI/dlt-viewer/pull/79
In the mentioned pull request I have added signed off commit and also resolved the merge conflict

**Comment by alexmucde** [comment]
Duplicate of #79

**Pull request closed without merging**
