### PR TITLE
Fix Dlt Viewer seg fault when dummy viewer is enabled manually

### PR DESCRIPTION
**Pull request by ashrivani**
Fix Dlt Viewer seg fault when dummy viewer is enabled manually

### CODE REVIEW

**Comment by alexmucde** [comment]
Hello @ashrivani 

can you please add a signed off statement with your Name and E-Mailadress to the Commit message?

Are the changes all related to the seg fault? Perhaps you can split the piull request into several pull reuqests, One thats fixing the seg fault and further one with the other changes.

    Alex

**Comment by ashrivani** [comment]
> Hello @ashrivani,
> 
> can you please add a signed off statement with your Name and E-Mailadress to the Commit message? See other commits in DLT Viewer.
> 
> Are the changes all related to the seg fault? Perhaps you can split the piull request into several pull reuqests, One thats fixing the seg fault and further one with the other changes.
> 
> ```
> Alex
> ```

I will create two  pull requests.
One for the seg fault .
Another  for the stdc++ linking .

**Comment by alexmucde** [comment]
@ashrivani Looks like you deleted the CMakeLists.txt files. Perhaps it is better to provide two new Pull requests and close this old Pull Request.

**Comment by ashrivani** [comment]
> @ashrivani Looks like you deleted the CMakeLists.txt files. Perhaps it is better to provide two new Pull requests and close this old Pull Request.

I will retain this pull request for the bug fix ,another i will create for the stdc++ library  linking  issue.

**Comment by alexmucde** [comment]
@ashrivani I have forgot to request a signed off statement in the commit message from you.

Can you provide a line like the following to me with your name and E-Mail address

Signed-off-by: Gernot Wirschal <gernot.wirschal@bmw.de>

Then i will fix this in the last commit.

**Comment by ashrivani** [comment]
Signed-off-by:Shrivani
shrivani@kpit.com

**Comment by ashrivani** [comment]
@alex: you had requested earlier , I missed to sign off my last commit

**Comment by alexmucde** [comment]
Thanks, i fixed it.

**Pull request merged**
