### PR TITLE
[Bugfix] Avoid error Message when cancelling open filter dialog

### PR DESCRIPTION
**Pull request by gobater**

### CODE REVIEW

**Comment by alexmucde** [comment]
@gobater Can you provide a signed off statement to your commit message?

**Review by alexmucde — APPROVED** [review]

**Comment by gobater** [comment]
@alexmucde: commit updated (signed)

**Comment by alexmucde** [comment]
I mean something like this:

Signed-off-by: Alexander Wenzel Alexander.AW.Wenzel@bmw.de

but with your name  and E-Mailaddress

**Comment by gobater** [comment]
OK, I hopefully got it right now!

**Pull request merged**
